// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrushLineChart: typeof import('./src/components/Charts/BrushLineChart.vue')['default']
    BubbleModal: typeof import('./src/components/Modal/BubbleModal.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/ColorPicker.vue')['default']
    ComparsionDialog: typeof import('./src/components/Dialog/comparsionDialog.vue')['default']
    DownloadCard: typeof import('./src/components/Modal/DownloadCard.vue')['default']
    DraggList: typeof import('./src/components/DraggList/DraggList.vue')['default']
    DynamicColumns: typeof import('./src/components/Table/DynamicColumns.vue')['default']
    GaugeChart: typeof import('./src/components/Charts/GaugeChart.vue')['default']
    LineChart: typeof import('./src/components/Charts/LineChart.vue')['default']
    MultiSelect: typeof import('./src/components/Select/MultiSelect.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutPullRefresh: typeof import('@nutui/nutui')['PullRefresh']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    ProgressCircle: typeof import('./src/components/ProgressBar/ProgressCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChart: typeof import('./src/components/Charts/ScatterChart.vue')['default']
    StatisticalChart: typeof import('./src/components/Charts/StatisticalChart.vue')['default']
    TableServer: typeof import('./src/components/Table/TableServer.vue')['default']
    TabPanel: typeof import('./src/components/Tabs/TabPanel.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
  }
}
