// generated by unplugin-vue-page1
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button'];
    NutToast: typeof import('@nutui/nutui-taro')['Toast'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
